covxray/covxray/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("website.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covxray/website/urls.py
"""
Website URLs

@author Akhil Kokani
"""
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
]

covxray/website/models.py
from django.db import models

# Create your models here.
class XrayImages(models.Model):
    xray_scan_img = models.FileField(upload_to="images/")

covxray/website/forms.py
"""
Website Forms.

Author: Akhil Kokani
"""
from django import forms
from .models import XrayImages

class XrayImageForm(forms.ModelForm):
    class Meta:
        model = XrayImages
        fields = ('xray_scan_img',)

covxray/website/views.py
"""
All the website views reside here.

Author: Akhil Kokani
"""
from django.shortcuts import render
from django.views import View



class HomeView(View):
    """
    This is the home page view.
    """

    def get(self, request):
        """
        If the request of GET type then render the home page.
        """
        return render(request, "home.html", {})


    def post(self, request):
        """
        If the request is of POST type then following is assumed:
        user is trying to upload an image which is an X-ray scan
        and should be used as an input for detecting COVID-19.
        """
        from django.http import JsonResponse
        from .forms import XrayImageForm
        from .models import XrayImages

        response = {
            "error": None # set this true if any error occurs while processing else false
            , "error_msg": ""
            , "has_covid": None # set this true if COVID detected
            , "is_normal": None # set this true if no COVID and viral detected
            , "has_viral": None # set this true if viral detected
        }

        form = XrayImageForm(request.POST, request.FILES)

        if form.is_valid():
            uploaded_image = form.cleaned_data['xray_scan_img']
            
            # create new instance, doing so will ease in accessing uploaded image url
            xray_image = XrayImages()
            xray_image.xray_scan_img = uploaded_image
            xray_image.save()

            # uploaded image url
            uploaded_image_url = xray_image.xray_scan_img.url

            response['error'] = False

            """
            Hey Vinayak,
            
            Invoke ML inference code here using the 'uploaded_image_url' variable.
            Once the inference results are available set the 'response' headers accordingly.
            
            Ex:
                if user has covid:
                    response['has_covid'] = True else False
                elif user has viral:
                    response['has_viral'] = True else False
                elif user is normal:
                    response['is_normal'] = True else False
            
            Just make sure at any instance any one of them should be set to true, say if
            user has covid then set 'has_covid' to true and other two as false.
            
            Once work is done, feel free to delete this comment.
            """

            return JsonResponse(response)
        else:
            response['error'] = True
            response['error_msg'] = "There was an error in your uploaded image. Try again with different image."
            return JsonResponse(response)

covxray/templates/home.html
{% comment %}
    Home page
    Through this single template user can view their COVID-19 results and 
    upload their scans as well.

    Author: Akhil Kokani
{% endcomment %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Detect COVID-19 using X-ray scans by Vinayak &amp; Akhil</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<body>
    
    <div class="wrapper">

        {% csrf_token %}
        
        <nav class="navbar navbar-expand-sm justify-content-center bg-dark navbar-dark">
            <a class="navbar-brand" href="{% url 'website:home' %}">CovXray</a>
            <span class="text-muted">Detect COVID-19 using X-ray scans</span>
        </nav>
        
        <div class="content-wrap">
            <div class="row">
                <div class="col-sm-9 image-content">
                    <div class="scanning-animation"></div>
                    <div class="xray-scan-preview"></div>
                    <style>
                        .xray-scan-preview {
                            background-image: url("{% static 'img/xray-scan-default.png' %}");
                            background-repeat: no-repeat;
                            background-size: cover;
                            height: 600px;
                        }
                    </style>
                </div>
                <div class="col-sm-3 panel-content">
                    <h6 class="text-secondary sub-title">ACTIONS</h6>

                    <input 
                        type="file" 
                        id="xray-image" 
                        style="position: absolute; top: -1000px;"
                    >

                    <button 
                        id="scan_xray"
                        type="button" 
                        class="btn btn-outline-primary btn-block"
                        >Select X-ray scan
                    </button>

                    <div class="results-content">
                        <hr class="mt-4 mb-4" style="border-color: var(--dark);">

                        <h6 class="text-secondary sub-title">RESULTS</h6>

                        <!-- X-ray scan results are shown in this -->
                        <p class="result-text text-danger">
                            Congratulations, you do not have COVID-19!
                        </p>

                        <!-- Scan duration is shown here -->
                        <p class="scan-duration text-muted">
                            Completed scan in 0.94 seconds
                        </p>
                    </div>
                </div>
            </div>

            <footer class="footer text-center mt-4">
                <p class="text-muted">Made Possible by <a href="">Vinayak J</a> &amp; <a href="">Akhil MK</a></p>
            </footer>
        </div>
    </div>

    <!-- Javascript -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/covxray.js' %}"></script>
</body>
</html>